version: '2'

services:
  app:
    image: node:12.6.0-alpine
    working_dir: /var/www
    # tty: true
    entrypoint: yarn run dev
    volumes:
      - .:/var/www
    ports:
      - 3000:3000

  postgres:
    image: rpopuc/postgres:11
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_HOST_PORT}:5432
